language: python
python:
  - "3.7"
dist: xenial
#addons:
#  chrome: stable
#before_install:
#  - # start your web application and listen on `localhost`
#  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
install: "pip install -r requirements.txt"
script: py.test
